from models.models import *

dummySensei = ModelSensei('17101999',
                          'Navdeep Sharma',
                          'navdeepisno1',
                          'navdeepisno1@gmail.com',
                          '17-10-1999', '126102',
                          'India',
                          'Haryana',
                          'Jind',
                          ['Hno 1128/25',
                           'Gurudwara Colony,Rohtak Road',
                           'Jind'],
                          'Near Jaat School',
                          'none',
                          '7015798026',
                          '100',
                          [ModelSkill('123', 'HTML,CSS,JS', 'WEB', '2'),
                           ModelSkill('121', 'DBMS', 'Computer Science', '4'),
                           ModelSkill('121', 'Operating System', 'Computer Science', '2')],
                          ["ensures students learn the language with an intensive learning strategies",
                           "ensures knowledge transfer are properly executed",
                           "able to maintain high standards of teaching",
                           "constant interaction between teacher and students."],
                          ModelRate(100, "month"), "2", "10", "Yes", "YES")
